### ISSUE TITLE
Maybe a typo in the NCE loss in page. 3 in the paper?

### ISSUE THREAD

**Issue by ManUtdMoon** [AGI-Labs/manipulate-by-seeing#1]
Dear Jianren and Sudeep,

Hello!

Thanks for your inspiring work! When I read about the NCE loss in the paper, I think there is a $-$ missing before the RHS because we want to maximize the similarity between $F(i_{t},a_t)$ and $i_g$ instead of minimizing it?

Are my thoughts right and if not, is there something wrong about my thoughts?

I am looking forward to your reply.

Regards,
Dongjie

**Comment by SudeepDasari** [comment]
Thanks for your interest in the paper! You're right that we want to maximize the similarity. I think the double negative in the definition for L_d may be accidental.

It may be helpful for you to see the implementation in code. We calculate [cosine similarities here](https://github.com/AGI-Labs/manipulate-by-seeing/blob/5f7a7c9a679be6c6fe0529431f1e0ac0fd664350/scripts/trainer.py#L80), and can efficiently compute the contrastive term using [CrossEntropyLoss](https://github.com/AGI-Labs/manipulate-by-seeing/blob/5f7a7c9a679be6c6fe0529431f1e0ac0fd664350/models/losses.py#L35).
